# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:  $

# ebuild generated by hackport 0.2.13

EAPI="3"

CABAL_FEATURES="lib profile haddock hscolour"
inherit haskell-cabal

DESCRIPTION="An infinite stream of random data"
HOMEPAGE="http://hackage.haskell.org/package/random-stream"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE="urandom openssl"

#TODO: add winrandom?

RDEPEND="dev-haskell/binary
		>=dev-lang/ghc-6.8.2
		openssl? ( dev-libs/openssl )"

DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.6"

src_prepare() {
	if use urandom; then
		if use openssl; then
			ewarn "This library only supports one random source. Disabling openssl."
		fi
		CABAL_CONFIGURE_FLAGS="--flags=have_urandom"
	elif use openssl; then
		CABAL_CONFIGURE_FLAGS="--flags=have_ssl"
	else
		die "You need one random source."
	fi

}
